/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apicacionfichajes.interfaz;

import apicacionfichajes.ManagerEmpleados;
import apicacionfichajes.ManagerFichas;
import apicacionfichajes.db.GestionDBConn;
import apicacionfichajes.gestionsql.GestionHelper;
import apicacionfichajes.gestionsql.SQLEmpleados;
import apicacionfichajes.gestionsql.SQLFichas;
import apicacionfichajes.modelos.Empleado;
import apicacionfichajes.modelos.Ficha;
import apicacionfichajes.modelos.QType;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/**
 *
 * @author adria
 */
public class EmpleadosGUI extends javax.swing.JFrame {

    GestionDBConn conexion;
    
    private DefaultListModel listModelEmp;
    
    private SQLEmpleados SQLE = new SQLEmpleados();
    private ManagerEmpleados ME;
    private Empleado empSelection = new Empleado();
    
    private Empleado loggedUser;
    
    private SQLFichas SQLF = new SQLFichas();   
    private ManagerFichas MF;
    private Ficha ficha = new Ficha();
    
    private GestionHelper GH = new GestionHelper();
    
    int codigo;
    
    /**
     * Creates new form EmpleadosGUI
     */
    public EmpleadosGUI() {
        initComponents();
        listModelEmp = new DefaultListModel();
        this.jListEmp.setModel(listModelEmp);
        ME = SQLE.listarEmpleados();
        MF = SQLF.listarFichas();
        this.showCodigo.setEnabled(false);
        popularScroll();     
    }

    private void popularScroll() {
        // Traemos los datos de Departamentos
        ME = SQLE.listarEmpleados();
        //Limpio el modelo
        this.listModelEmp.clear();
        // Recorro el listado de Departamentos
        for (int i = 0; i < ME.size(); i++) {
            listModelEmp.addElement(ME.get(i).toSimpleString());
        }

    }

    private void numpadAction(int code) {
        if (showCodigo.isEnabled()) {
            if (showCodigo.getText().length() >= 5) {
                JOptionPane.showMessageDialog(null,
                        "Error: El codigo no puede ser de más de 4 digitos", "Error!",
                        JOptionPane.ERROR_MESSAGE);

            } else if (showCodigo.getText().length() <= 4) {
                this.showCodigo.setText(showCodigo.getText() + "*");
                codigo = Integer.parseInt(Integer.toString(codigo) + code);
            }
        } else {
            JOptionPane.showMessageDialog(null,
                    "Selecciona un usuario antes de introducir el codigo", "Información",
                    JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SelectionAndCode = new javax.swing.JPanel();
        UserListScrollPaNel = new javax.swing.JScrollPane();
        jListEmp = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        selectedUser = new javax.swing.JLabel();
        codePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        showCodigo = new javax.swing.JTextField();
        KeypadPanel = new javax.swing.JPanel();
        Numpad = new javax.swing.JPanel();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        boton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        boton0 = new javax.swing.JButton();
        botonOk = new javax.swing.JButton();
        botonReset = new javax.swing.JButton();
        Title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(600, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        SelectionAndCode.setBackground(new java.awt.Color(255, 255, 255));
        SelectionAndCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jListEmp.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jListEmp.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jListEmpMousePressed(evt);
            }
        });
        UserListScrollPaNel.setViewportView(jListEmp);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Seleccion:");

        selectedUser.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        selectedUser.setForeground(new java.awt.Color(0, 0, 0));

        codePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        codePanel.setForeground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("CÓDIGO:");

        showCodigo.setText(" ");

        javax.swing.GroupLayout codePanelLayout = new javax.swing.GroupLayout(codePanel);
        codePanel.setLayout(codePanelLayout);
        codePanelLayout.setHorizontalGroup(
            codePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(codePanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(codePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(showCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        codePanelLayout.setVerticalGroup(
            codePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(codePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(showCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SelectionAndCodeLayout = new javax.swing.GroupLayout(SelectionAndCode);
        SelectionAndCode.setLayout(SelectionAndCodeLayout);
        SelectionAndCodeLayout.setHorizontalGroup(
            SelectionAndCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectionAndCodeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SelectionAndCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(SelectionAndCodeLayout.createSequentialGroup()
                        .addGroup(SelectionAndCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(UserListScrollPaNel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(selectedUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        SelectionAndCodeLayout.setVerticalGroup(
            SelectionAndCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectionAndCodeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserListScrollPaNel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectedUser, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(codePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        KeypadPanel.setBackground(new java.awt.Color(255, 255, 255));

        Numpad.setLayout(new java.awt.GridLayout(4, 4));

        boton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        boton1.setText("1");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        Numpad.add(boton1);

        boton2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        boton2.setText("2");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        Numpad.add(boton2);

        boton3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        boton3.setText("3");
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });
        Numpad.add(boton3);

        boton4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        boton4.setText("4");
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });
        Numpad.add(boton4);

        boton5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        boton5.setText("5");
        boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton5ActionPerformed(evt);
            }
        });
        Numpad.add(boton5);

        boton6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        boton6.setText("6");
        boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton6ActionPerformed(evt);
            }
        });
        Numpad.add(boton6);

        boton7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        boton7.setText("7");
        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });
        Numpad.add(boton7);

        jButton8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        Numpad.add(jButton8);

        boton9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        boton9.setText("9");
        boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton9ActionPerformed(evt);
            }
        });
        Numpad.add(boton9);

        boton0.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        boton0.setText("0");
        boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton0ActionPerformed(evt);
            }
        });
        Numpad.add(boton0);

        botonOk.setBackground(new java.awt.Color(0, 102, 204));
        botonOk.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        botonOk.setText("OK");
        botonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOkActionPerformed(evt);
            }
        });
        Numpad.add(botonOk);

        botonReset.setBackground(new java.awt.Color(255, 51, 51));
        botonReset.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botonReset.setText("REINICIAR");
        botonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResetActionPerformed(evt);
            }
        });
        Numpad.add(botonReset);

        javax.swing.GroupLayout KeypadPanelLayout = new javax.swing.GroupLayout(KeypadPanel);
        KeypadPanel.setLayout(KeypadPanelLayout);
        KeypadPanelLayout.setHorizontalGroup(
            KeypadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeypadPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Numpad, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addContainerGap())
        );
        KeypadPanelLayout.setVerticalGroup(
            KeypadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeypadPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Numpad, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        Title.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Title.setText("APLICACIÓN DE FICHAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(SelectionAndCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(KeypadPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(Title)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(SelectionAndCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(KeypadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListEmpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListEmpMousePressed
        reset();
        this.selectedUser.setText("");
        empSelection = this.ME.get(this.jListEmp.getSelectedIndex());
        this.selectedUser.setText(empSelection.toSimpleString());
        this.showCodigo.setEnabled(true);
        
    }//GEN-LAST:event_jListEmpMousePressed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        numpadAction(1);
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        numpadAction(2);
        
    }//GEN-LAST:event_boton2ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        numpadAction(3);
    }//GEN-LAST:event_boton3ActionPerformed

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
        numpadAction(4);
    }//GEN-LAST:event_boton4ActionPerformed

    private void boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton5ActionPerformed
        numpadAction(5);
    }//GEN-LAST:event_boton5ActionPerformed

    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6ActionPerformed
        numpadAction(6);
    }//GEN-LAST:event_boton6ActionPerformed

    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
        numpadAction(7);
    }//GEN-LAST:event_boton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        numpadAction(8);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton9ActionPerformed
        numpadAction(9);
    }//GEN-LAST:event_boton9ActionPerformed

    private void boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton0ActionPerformed
        numpadAction(0);
    }//GEN-LAST:event_boton0ActionPerformed

    private void botonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOkActionPerformed
        empSelection = this.ME.get(this.jListEmp.getSelectedIndex());
        Empleado empCode = new Empleado();
        empCode.setCodigo(codigo);
        boolean logged = GH.logearEmpleado(empSelection, empCode);
        if(logged){
            loggedUser = empSelection;
        } else {
            JOptionPane.showMessageDialog(null,
                    "El código introducido no es correcto, prueba a intentarlo de nuevo.", "Error de Logeo",
                    JOptionPane.ERROR_MESSAGE);
        } 
        reset();
        
    }//GEN-LAST:event_botonOkActionPerformed

    private void botonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResetActionPerformed
         reset();
    }//GEN-LAST:event_botonResetActionPerformed

    
    private void reset() {
        this.selectedUser.setText("");
        this.showCodigo.setText(" ");
        this.codigo = 0;
        empSelection = null;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpleadosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpleadosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpleadosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpleadosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpleadosGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel KeypadPanel;
    private javax.swing.JPanel Numpad;
    private javax.swing.JPanel SelectionAndCode;
    private javax.swing.JLabel Title;
    private javax.swing.JScrollPane UserListScrollPaNel;
    private javax.swing.JButton boton0;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton9;
    private javax.swing.JButton botonOk;
    private javax.swing.JButton botonReset;
    private javax.swing.JPanel codePanel;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jListEmp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel selectedUser;
    private javax.swing.JTextField showCodigo;
    // End of variables declaration//GEN-END:variables
}
